"""Draft presets: scoring x league-size -> (LeagueConfig, pre-generated VORP table path).

Single canonical skill roster; only the ruleset and team count vary across the 3x3 grid.
The board's dropdowns resolve to a DraftPreset; the whole draft + the end-of-draft sim run
under it. Tables are generated by scripts/generate_preset_vorp_tables.py."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from projections.draft.league_config import LeagueConfig
from projections.schemas import RosterSlot, Ruleset

SCORING_KEYS: tuple[str, ...] = ("half", "ppr", "std")
TEAM_SIZES: tuple[int, ...] = (10, 12, 16)
DEFAULT_SCORING = "half"
DEFAULT_TEAMS = 16

_RULESETS: dict[str, Ruleset] = {
    "half": Ruleset.espn_half(),
    "ppr": Ruleset.espn_ppr(),
    "std": Ruleset.standard(),
}
_SCORING_LABELS: dict[str, str] = {"half": "Half-PPR", "ppr": "Full PPR", "std": "Standard"}
# Canonical skill roster (no K/DST -- consensus is skill-only); matches the user's draft.
_SKILL_ROSTER: dict[RosterSlot, int] = {
    RosterSlot.QB: 1,
    RosterSlot.RB: 2,
    RosterSlot.WR: 3,
    RosterSlot.TE: 1,
    RosterSlot.FLEX: 1,
    RosterSlot.BENCH: 9,
}
# Relative to the repo root; callers that perform I/O must resolve it against the project root.
_TABLE_DIR = Path("data/vorp_2026")


@dataclass(frozen=True)
class DraftPreset:
    scoring_key: str
    n_teams: int
    label: str
    league_config: LeagueConfig
    table_path: Path


def _skill_config(scoring_key: str, n_teams: int) -> LeagueConfig:
    return LeagueConfig(
        name=f"{scoring_key}_{n_teams}team_2026",
        n_teams=n_teams,
        roster_slots=dict(_SKILL_ROSTER),
        ruleset=_RULESETS[scoring_key],
    )


def get_preset(scoring_key: str, n_teams: int) -> DraftPreset:
    if scoring_key not in _RULESETS:
        raise ValueError(f"unknown scoring key {scoring_key!r}; expected one of {SCORING_KEYS}")
    if n_teams not in TEAM_SIZES:
        raise ValueError(f"unsupported n_teams {n_teams}; expected one of {TEAM_SIZES}")
    return DraftPreset(
        scoring_key=scoring_key,
        n_teams=n_teams,
        label=f"{_SCORING_LABELS[scoring_key]} / {n_teams}-team",
        league_config=_skill_config(scoring_key, n_teams),
        table_path=_TABLE_DIR / f"{scoring_key}_{n_teams}team.parquet",
    )


def materialize_league_config(preset: DraftPreset, *, config_dir: Path | None = None) -> Path:
    """Write the preset's in-memory `LeagueConfig` to a JSON file and return its path.

    The live board's autosave persists the league config as a *path* (the CLI's
    `load_draft_state` and `LiveDraftSession.load` both read it via `read_text()`), so a
    preset-started draft must point at a real file to be resumable — without this it would
    serialize `league_config: "."` and fail to resume. Idempotent: rewrites the canonical JSON
    (next to the preset's table by default) each call. The file is an untracked artifact, like
    the VORP tables.
    """
    target_dir = config_dir if config_dir is not None else preset.table_path.parent
    target_dir.mkdir(parents=True, exist_ok=True)
    path = target_dir / f"{preset.scoring_key}_{preset.n_teams}team.league.json"
    path.write_text(preset.league_config.model_dump_json(indent=2))
    return path


__all__ = [
    "DEFAULT_SCORING",
    "DEFAULT_TEAMS",
    "SCORING_KEYS",
    "TEAM_SIZES",
    "DraftPreset",
    "get_preset",
    "materialize_league_config",
]
